AWSTemplateFormatVersion: "2010-09-09"
Description: Ec2-demo

Resources:
  Ec2Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      InstanceType: ${InstanceType}
      ImageId: ${ImageId}
      SecurityGroupIds:
        - !Ref MySecGrp1
      KeyName: ${keyname}

  MySecGrp1:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: ${AWS::StackName}
      GroupDescription: Open ports 22 for ssh. 80 for http
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: "22"
          ToPort: "22"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "80"
          ToPort: "80"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8080"
          ToPort: "8080"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "8443"
          ToPort: "8443"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "443"
          ToPort: "443"
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: "0"
          ToPort: "65535"
          CidrIp: 0.0.0.0/0
